name: uptimekuma
display_name: Uptime Kuma
description: Self-hosted uptime monitoring tool
version: 2.0.2
category: monitoring
port: 3001
url: https://uptime.kuma.pet
priority: 80

networks: []
appdata_dirs: [uptimekuma]
media_dirs: []

secrets:
