name: qbittorrent
display_name: qBittorrent
description: BitTorrent client with web UI
version: 5.1.4
category: servarr
port: 8080
url: https://www.qbittorrent.org
priority: 65

networks: [media-net]
appdata_dirs: [qbittorrent]
media_dirs: [Downloads]

secrets:
