name: jellyseerr
display_name: Jellyseerr
description: Media request management for Jellyfin
version: 2.7.3
category: servarr
port: 5055
url: https://github.com/Fallenbagel/jellyseerr
priority: 70

networks: [media-net]
appdata_dirs: [jellyseerr]
media_dirs: []

depends_on: [jellyfin]

secrets:
